roanoke_lib:
    resource: "@RoanokeLibBundle/Controller/"
    type:     annotation
    prefix:   /

story:
    path:      /
    defaults:  { _controller: RoanokeLibBundle:Story:new }

        
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
